<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AngleSharp" Version="1.5.0" />
		<PackageReference Include="KubernetesClient" Version="19.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
		<PackageReference Include="Microsoft.Playwright" Version="1.60.0" />
		<PackageReference Include="SharpCompress" Version="0.49.1" />
		<PackageReference Include="System.Drawing.Common" Version="10.0.9" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Common\Mihaylov.Common.Generic\Mihaylov.Common.Generic.csproj" />
	  <ProjectReference Include="..\Mihaylov.Api.Other.Contracts\Mihaylov.Api.Other.Contracts.csproj" />
	</ItemGroup>

</Project>
