<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<Version>0.1.0</Version>
		<PackageId>Mihaylov.Common.Host</PackageId>
		<Description>Shared Host utilities.</Description>
		<Authors>Mihaylov</Authors>
	</PropertyGroup>

	<PropertyGroup>
		<DebugType>embedded</DebugType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IncludeSymbols>true</IncludeSymbols>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mihaylov.Common.Generic" Version="0.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.19" />		
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="8.1.4" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.4" />
	</ItemGroup>	
</Project>
