// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mihaylov.Api.Other.Database.Shows;

#nullable disable

namespace Mihaylov.Api.Other.Database.Migrations
{
    [DbContext(typeof(MihaylovOtherShowDbContext))]
    partial class MihaylovOtherShowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("show")
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mihaylov.Api.Other.Database.Shows.Models.Band", b =>
                {
                    b.Property<int>("BandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BandId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BandId")
                        .HasName("BandId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Bands", "show");
                });

            modelBuilder.Entity("Mihaylov.Api.Other.Database.Shows.Models.Concert", b =>
                {
                    b.Property<int>("ConcertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConcertId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TicketProviderId")
                        .HasColumnType("int");

                    b.HasKey("ConcertId")
                        .HasName("ConcertId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TicketProviderId");

                    b.ToTable("Concerts", "show");
                });

            modelBuilder.Entity("Mihaylov.Api.Other.Database.Shows.Models.ConcertBand", b =>
                {
                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("BandId", "ConcertId");

                    b.HasIndex("ConcertId");

                    b.ToTable("ConcertBands", "show");
                });

            modelBuilder.Entity("Mihaylov.Api.Other.Database.Shows.Models.Currency", b =>
                {
                    b.Property<byte>("CurrencyId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("CurrencyId")
                        .HasName("CurrencyId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Currencies", "show");

                    b.HasData(
                        new
                        {
                            CurrencyId = (byte)1,
                            Name = "BGN"
                        },
                        new
                        {
                            CurrencyId = (byte)2,
                            Name = "EUR"
                        });
                });

            modelBuilder.Entity("Mihaylov.Api.Other.Database.Shows.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LocationId")
                        .HasName("LocationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations", "show");
                });

            modelBuilder.Entity("Mihaylov.Api.Other.Database.Shows.Models.TicketProvider", b =>
                {
                    b.Property<int>("TickerProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TickerProviderId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TickerProviderId")
                        .HasName("TickerProviderId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TicketProviders", "show");
                });

            modelBuilder.Entity("Mihaylov.Api.Other.Database.Shows.Models.Concert", b =>
                {
                    b.HasOne("Mihaylov.Api.Other.Database.Shows.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mihaylov.Api.Other.Database.Shows.Models.Location", "Location")
                        .WithMany("Concerts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mihaylov.Api.Other.Database.Shows.Models.TicketProvider", "TicketProvider")
                        .WithMany("Concerts")
                        .HasForeignKey("TicketProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Location");

                    b.Navigation("TicketProvider");
                });

            modelBuilder.Entity("Mihaylov.Api.Other.Database.Shows.Models.ConcertBand", b =>
                {
                    b.HasOne("Mihaylov.Api.Other.Database.Shows.Models.Band", "Band")
                        .WithMany("ConcertBands")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mihaylov.Api.Other.Database.Shows.Models.Concert", "Concert")
                        .WithMany("ConcertBands")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("Mihaylov.Api.Other.Database.Shows.Models.Band", b =>
                {
                    b.Navigation("ConcertBands");
                });

            modelBuilder.Entity("Mihaylov.Api.Other.Database.Shows.Models.Concert", b =>
                {
                    b.Navigation("ConcertBands");
                });

            modelBuilder.Entity("Mihaylov.Api.Other.Database.Shows.Models.Location", b =>
                {
                    b.Navigation("Concerts");
                });

            modelBuilder.Entity("Mihaylov.Api.Other.Database.Shows.Models.TicketProvider", b =>
                {
                    b.Navigation("Concerts");
                });
#pragma warning restore 612, 618
        }
    }
}
