version: '3.4'
services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: Passw0rd2020
      MSSQL_PID: Express
    ports:
      - '1433:1433'
  dockerapi:
    build:
      context: .
      dockerfile: DockerApi/Dockerfile
    ports:
       - "8080:80"
    environment:
      dbServer: sql-server
      dbPort: '1433'
      dbUser: SA
      dbPassword: Passw0rd2020
      DbName: ColourDb
