version: '3.4'

services:
  mihaylov.webui:
    image: ${DOCKER_REGISTRY-}mihaylovwebui
    build:
      context: .
      dockerfile: Web/Mihaylov.WebUI/Dockerfile

  mihaylov.users.server:
    image: ${DOCKER_REGISTRY-}mihaylovusersserver
    build:
      context: .
      dockerfile: Users/Mihaylov.Users.Server/Dockerfile

