<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<Version>0.1.0</Version>
		<PackageId>Mihaylov.Common.Database</PackageId>
		<Description>Shared Database utilities.</Description>
		<Authors>Mihaylov</Authors>
	</PropertyGroup>
	
	<PropertyGroup>
		<DebugType>embedded</DebugType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IncludeSymbols>true</IncludeSymbols>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.26" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
