#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /source

COPY ["Web/Mihaylov.WebUI/Mihaylov.WebUI.csproj", "Web/Mihaylov.WebUI/"]
RUN dotnet restore "Web/Mihaylov.WebUI/Mihaylov.WebUI.csproj" -r linux-arm

COPY . .
WORKDIR "/source/Web/Mihaylov.WebUI"
RUN dotnet publish "Mihaylov.WebUI.csproj" -c release -o /app -r linux-arm --self-contained false --no-restore

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim-arm32v7 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY --from=build /app .
#ENTRYPOINT ["dotnet", "Mihaylov.WebUI.dll"]
