// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mihaylov.Api.Gear.Infrastructure.Persistence;

#nullable disable

namespace Mihaylov.Api.Gear.Infrastructure.Migrations
{
    [DbContext(typeof(MihaylovGearDbContext))]
    partial class MihaylovGearDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Entities.GearNode", b =>
                {
                    b.Property<long>("GearNodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GearNodeId"), 1000L);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<long?>("InventoryItemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsExcluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPacked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("NodeTypeId")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.HasKey("GearNodeId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GroupId");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("NodeTypeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("TripId", "ParentId");

                    b.ToTable("GearNodes");
                });

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<long>("InventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InventoryItemId"), 1000L);

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("ItemStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("InventoryItemId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ItemStatusId");

                    b.HasIndex("Name");

                    b.HasIndex("ShopId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Entities.Trip", b =>
                {
                    b.Property<long>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TripId"), 100L);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("TripId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Enums.ItemStatusDb", b =>
                {
                    b.Property<int>("ItemStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ItemStatusId");

                    b.ToTable("ItemStatuses");

                    b.HasData(
                        new
                        {
                            ItemStatusId = 1,
                            Name = "Active"
                        },
                        new
                        {
                            ItemStatusId = 2,
                            Name = "Broken"
                        },
                        new
                        {
                            ItemStatusId = 3,
                            Name = "Lost"
                        },
                        new
                        {
                            ItemStatusId = 4,
                            Name = "Retired"
                        },
                        new
                        {
                            ItemStatusId = 5,
                            Name = "Ignored"
                        });
                });

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Enums.NodeTypeDb", b =>
                {
                    b.Property<int>("NodeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NodeTypeId");

                    b.ToTable("NodeTypes");

                    b.HasData(
                        new
                        {
                            NodeTypeId = 1,
                            Name = "Group"
                        },
                        new
                        {
                            NodeTypeId = 2,
                            Name = "Category"
                        },
                        new
                        {
                            NodeTypeId = 3,
                            Name = "Item"
                        });
                });

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Lookups.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Lookups.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Lookups.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurrencyId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Lookups.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Lookups.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Entities.GearNode", b =>
                {
                    b.HasOne("Mihaylov.Api.Gear.Core.Domain.Lookups.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mihaylov.Api.Gear.Core.Domain.Lookups.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mihaylov.Api.Gear.Core.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mihaylov.Api.Gear.Core.Domain.Enums.NodeTypeDb", "NodeType")
                        .WithMany()
                        .HasForeignKey("NodeTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mihaylov.Api.Gear.Core.Domain.Entities.GearNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mihaylov.Api.Gear.Core.Domain.Entities.Trip", "Trip")
                        .WithMany("Nodes")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Group");

                    b.Navigation("InventoryItem");

                    b.Navigation("NodeType");

                    b.Navigation("Parent");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("Mihaylov.Api.Gear.Core.Domain.Lookups.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mihaylov.Api.Gear.Core.Domain.Lookups.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mihaylov.Api.Gear.Core.Domain.Lookups.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mihaylov.Api.Gear.Core.Domain.Enums.ItemStatusDb", "ItemStatus")
                        .WithMany()
                        .HasForeignKey("ItemStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mihaylov.Api.Gear.Core.Domain.Lookups.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsMany("Mihaylov.Api.Gear.Core.Domain.Entities.KitContentItem", "KitContents", b1 =>
                        {
                            b1.Property<long>("InventoryItemId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("InventoryItemId", "Id");

                            b1.ToTable("InventoryItems");

                            b1.ToJson("KitContents");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Currency");

                    b.Navigation("ItemStatus");

                    b.Navigation("KitContents");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Entities.GearNode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Mihaylov.Api.Gear.Core.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
