//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mihaylov.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MihaylovDbContext : DbContext
    {
        public MihaylovDbContext()
            : base("name=MihaylovDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnswerType> AnswerTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<EthnicityType> EthnicityTypes { get; set; }
        public virtual DbSet<OrientationType> OrientationTypes { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
    }
}
