//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mihaylov.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EthnicityType
    {
        public EthnicityType()
        {
            this.Persons = new HashSet<Person>();
        }
    
        public int EthnicityTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Person> Persons { get; set; }
    }
}
