//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mihaylov.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonId { get; set; }
        public string Username { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastBroadcastDate { get; set; }
        public Nullable<System.DateTime> AskDate { get; set; }
        public int Age { get; set; }
        public int CountryId { get; set; }
        public int EthnicityTypeId { get; set; }
        public int OrientationTypeId { get; set; }
        public int AnswerTypeId { get; set; }
        public Nullable<decimal> Answer { get; set; }
        public Nullable<int> AnswerUnitTypeId { get; set; }
        public Nullable<decimal> AnswerConverted { get; set; }
        public string Comments { get; set; }
        public string RecordsPath { get; set; }
        public bool IsAccountDisabled { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual AnswerType AnswerType { get; set; }
        public virtual Country Country { get; set; }
        public virtual UnitType UnitType { get; set; }
        public virtual EthnicityType EthnicityType { get; set; }
        public virtual OrientationType OrientationType { get; set; }
    }
}
