//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mihaylov.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonId { get; set; }
        public string Username { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime AskDate { get; set; }
        public int Age { get; set; }
        public int CountryId { get; set; }
        public int EthnicityId { get; set; }
        public int SexPreferenceId { get; set; }
        public int AnswerTypeId { get; set; }
        public Nullable<decimal> Answer { get; set; }
        public Nullable<int> AnswerUnitId { get; set; }
        public Nullable<decimal> AnswerConverted { get; set; }
        public string Comments { get; set; }
        public string RecordsPath { get; set; }
    
        public virtual Answer Answer1 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Ethnicity Ethnicity { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual SexPreference SexPreference { get; set; }
    }
}
