//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mihaylov.Database.Dictionaries
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Level()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public int LevelId { get; set; }
        public int LearningSystemId { get; set; }
        public string Name { get; set; }
        public string Descrition { get; set; }
        public Nullable<int> ModulesStartNumber { get; set; }
        public Nullable<int> ModulesEndNumber { get; set; }
    
        public virtual LearningSystem LearningSystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
