//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mihaylov.Database.Dictionaries
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrepositionType
    {
        public int PrepositionTypeId { get; set; }
        public int LanguageId { get; set; }
        public string Value { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
