//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mihaylov.Database.Dictionaries
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.Tests1 = new HashSet<Test>();
            this.Records = new HashSet<Record>();
        }
    
        public int TestId { get; set; }
        public Nullable<int> PreviousTestId { get; set; }
        public string UserId { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> ModuleStartNumber { get; set; }
        public Nullable<int> ModuleEndNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> CorrectAnswers { get; set; }
        public Nullable<int> TotalRecords { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests1 { get; set; }
        public virtual Test Test1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Cours Cours { get; set; }
    }
}
